lib/dlt_web/router.ex
defmodule DLTWeb.Router do
  use DLTWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", DLTWeb do
    pipe_through :browser

    get "/", ScenarioController, :index

    scope "/scenarios" do
      resources "/", ScenarioController
      post "/start_session", ScenarioController, :start_session
    end

    resources "/workers", WorkerController
  end

  import Phoenix.LiveDashboard.Router

  scope "/" do
    pipe_through :browser
    live_dashboard "/dashboard", metrics: DLTWeb.Telemetry
  end
end

lib/dlt_web/views/layout_view.ex
defmodule DLTWeb.LayoutView do
  use DLTWeb, :view
end

lib/dlt_web/templates/layout/app.html.eex
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Roman Chvanikov">
  <title>DLT - Distributed Load Testing application</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" integrity="sha256-DU9iQBJ89dHP2iyusCg++0ych55DAx8QL6P8CYU64bI=" crossorigin="anonymous">
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
</head>
<body>
  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">DLT</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  </header>

  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3">
          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Application</span>
          </h6>
          <ul class="nav flex-column">
            <li class="nav-item">
              <%= link to: Routes.scenario_path(@conn, :index), class: "nav-link" do %>
                <span data-feather="home"></span>
                Scenarios
              <% end %>
            </li>

            <li class="nav-item">
              <%= link to: Routes.worker_path(@conn, :index), class: "nav-link" do %>
                <span data-feather="home"></span>
                Workers
              <% end %>
            </li>
          </ul>

          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>System</span>
          </h6>
          <ul class="nav flex-column mb-2">
            <li class="nav-item">
              <%= link to: Routes.live_dashboard_path(@conn, :home), class: "nav-link" do %>
                <span data-feather="plus-circle"></span>
                Live Dashboard
              <% end %>
            </li>
          </ul>
        </div>
      </nav>

      <%= @inner_content %>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha256-G72xkTLOzlEDwKKRngkyDtxmh6s4efw7sdKPDw+l1F8=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
  <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>